# Healthy user simulation profile
# Location: config/simulation_profiles/healthy_user.toml

[profile]
name = "healthy_user"
description = "Healthy adult with normal muscle function in clinical setting"

[muscle_characteristics]
fiber_composition = "Balanced"
strength_level = "Normal"
fatigue_resistance = "Normal"
neural_efficiency = 0.85

[noise_characteristics]
environment_type = "Clinical"
electrode_quality = "Clinical"
signal_conditioning = "Standard"

[simulation_config]
profile_name = "healthy_user"
sample_rate_hz = 2000
channel_count = 8

[simulation_config.muscle_config]
fiber_recruitment_curve = 0.34
maximum_voluntary_contraction = 1.0
fatigue_rate = 0.01
recovery_rate = 0.05

[simulation_config.noise_config]
thermal_noise_power_dbm = -65.0
powerline_frequency_hz = 50.0
powerline_amplitude_factor = 0.01
electrode_impedance_base = 5000.0
electrode_impedance_variance = 1000.0

[simulation_config.artifact_config]
motion_artifact_probability = 0.005
motion_artifact_amplitude = 0.15
electrode_pop_probability = 0.0005
cable_movement_probability = 0.0025

[[gesture_library]]
gesture_type = "HandClose"
variability_factor = 0.15
success_rate = 0.95


[[gesture_library]]
gesture_type = "HandOpen"
variability_factor = 0.20
success_rate = 0.92

[gesture_library.activation_profile]
onset_time_ms = 120.0
peak_time_ms = 250.0
offset_time_ms = 180.0
amplitude_consistency = 0.85